- hosts: minecraft
  become: true
  tasks:
    - name: Install Java
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Create Minecraft directory
      file:
        path: /home/ec2-user/minecraft
        state: directory
        owner: ec2-user

    - name: Download server jar
      get_url:
        url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /home/ec2-user/minecraft/server.jar
        owner: ec2-user

    - name: Accept EULA
      copy:
        dest: /home/ec2-user/minecraft/eula.txt
        content: "eula=true\n"
        owner: ec2-user

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/minecraft
          ExecStart=/usr/bin/java -Xmx1G -Xms1G -jar server.jar nogui
          ExecStop=/bin/kill -s SIGINT $MAINPID
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify:
        - reload systemd

    - name: Start Minecraft
      systemd:
        name: minecraft
        enabled: yes
        state: started

  handlers:
    - name: reload systemd
      command: systemctl daemon-reexec

